version: '2'
services:
  valkey:
    image: valkey/valkey:alpine3.20
  postgres:
    image: 16.3-alpine3.20
    environment:
      POSTGRES_USER: rest_api_user
      POSTGRES_PASSWORD: rest_api_pass
      POSTGRES_DB: rest_api_db
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/rest-api
      - /rest-api/node_modules
    depends_on:
      - postgres
      - valkey
    environment:
      DATABASE_URL: postgres://rest_api_user:rest_api_pass@postgres/rest_api_db
      REDIS_URL: http://redis
    command: ["/bin/wait_for_it.sh", "postgres:5432", "--",
              "/bin/wait_for_it.sh", "redis:6379", "--",
              "/usr/bin/cargo", "test"]
